### ISSUE TITLE
ssh bot set-token documentation

### ISSUE THREAD

**Issue by MatildeTristany** [franaudo/codebots#7]
* codebots version: 0.8.1
* Python version: 3.8
* Operating System: MacOS

### Description

the `sshbot set-token` command does not accept the password argument.
Also the documentation is outdated

**Comment by franaudo** [comment]
solved with commit https://github.com/franaudo/codebots/commit/511ff346bf2f9488b981908b2f97b7e4d1444d85 in release `v0.9`
